### ISSUE TITLE
Incorporating additional infos to LSTM

### ISSUE THREAD

**Issue by Cuky88** [chibui191/bitcoin_volatility_forecasting#1]
Hi,
thanks for the great work.

I'm curious about adding additional variables to a LSTM. Do you have some resources how this could be done?

**Comment by chibui191** [comment]
Hi,
I think as long as you keep its shape in the same format pointed out in the Multivariate LSTM section, you should be able to pass it in. Here’s the template for the shape btw:

[batch_size, n_past, input_dims]

Cheers!
